/*
  sinh vien act
*/

export const XEMTHONGTINSINHVIEN_SUCCESS = "sinhvien/XEMTHONGTINSINHVIEN_SUCCESS";
export const XEMTHONGTINSINHVIEN_FAILED = "sinhvien/XEMTHONGTINSINHVIEN_FAILED";

export const CHINHSUATHONGTINSINHVIEN_SUCCESS = "sinhvien/CHINHSUATHONGTINSINHVIEN_SUCCESS";
export const CHINHSUATHONGTINSINHVIEN_FAILED = "sinhvien/CHINHSUATHONGTINSINHVIEN_FAILED";




